### ISSUE TITLE
Navigation button hovers look awry on macOs

### ISSUE THREAD

**Issue by rollecode** [jpminor/mailspring-isaac-light-theme#2]
Hello. Noticed the button hovers don't look exactly like they perhaps should:

![Screenshot](https://i.imgur.com/IFmb7Xw.png "Screenshot")

**Comment by jpminor** [comment]
This is one I've played around with but haven't been able to correct. I've noticed that it's only when the window isn't in focus - same on your end? The image file itself may be the culprit as I scaled a lot of the icons down as well to gain some sharpness.

On Thu, Feb 7, 2019 at 12:19 AM, Roni Laukkarinen <notifications@github.com> wrote:
Hello. Noticed the button hovers don't look exactly like they perhaps should:

[https://camo.githubusercontent.com/efe1aa939ba35d6e219f5f2bdfc097fdd515e74b/68747470733a2f2f692e696d6775722e636f6d2f49466d623758772e706e67]

**Comment by rollecode** [comment]
When window isn't in focus, it's even different issue, didn't notice that before but it looks like this:

![Screenshot](https://i.imgur.com/ZIVY3th.png "Screenshot")

I can also look at this when I have time and send a pull request. But might take some time because atm quite busy.

**Comment by rollecode** [comment]
When focus and not hovered, the buttons look round and okay:

![Screenshot](https://i.imgur.com/IrHdaJ2.png "Screenshot")

**Comment by jpminor** [comment]
Yep, that’s what I get as well. I do recall at some point seeing an issue posted in mailspring’s repository about this.
Maybe the solution for right now is to try and do it with pure css, I just looked again and there isn't a 2x image in the package so the image isn’t sufficient to work with. I may have actually added border radius to the controls to do what I could.

Jon
On Thu, Feb 7, 2019 at 12:40 AM, Roni Laukkarinen <notifications@github.com> wrote:
When window isn't in focus, it's even different issue, didn't notice that before but it looks like this:

[https://camo.githubusercontent.com/b6f6fc29a26c319ffee5e208e394fa521708e987/68747470733a2f2f692e696d6775722e636f6d2f5a4956593374682e706e67]

I can also look at this when I have time and send a pull request. But might take some time because atm quite busy.

**Comment by rollecode** [comment]
Here's my [pull request](https://github.com/jpminor/mailspring-isaac-light-theme/pull/3).

**Comment by rollecode** [comment]
Any reason this is closed? haven't got the time to investigate it further, but what we now know is that for retina screens it works, but on non-retina screen it doesn't. Thought to ping because I usually work on my external screen that is not retina. So can this be reopened?

**Comment by rollecode** [comment]
Side note: If you don't define **any** background-size for `.toolbar-window-controls button`, it magically works, but currently not able to test on retina screens / all scenarios.

**Comment by jpminor** [comment]
Removed the background size. I'm going to keep it closed because the until the image file is replaced with a 2x image there's nothing that can be done to make it clear. It's not an issue with the theme.
